Various updates
RoleModel/rolemodel-design-system pull request #5
Opened 2022-05-25 21:23 UTC by Jeremy-Walton

## Task

## Why?

In effort to make this releasable, we want to take all our learnings and make them consistent here

## What Changed

* [X] Change token prefix from `rms` to `rm`
* [X] Change `colors` to `color` in tokens
* [X] Clean up comments from tom zelect
* [X] Use material symbols instead of material icons
* [X] Add z index tokens
* [X] Update font scale to be 1rem = 10px based and simplified
* [X] Update space scale similarly ^
* [X] Update default font to Noto Sans and include Noto Serif as an option
* [X] Clean up breakpoints by moving them into the base them, adding better docs, and making the names consistent.
* [ ] Update buttons to follow different standard. primary is main, secondary is outline, tertiary is ???? instead of having primary/secondary/tertiary be the color and then having outline and other variations for all those.

2022-05-25 21:29 UTC, Jeremy-Walton commented on README.md
> +  --rm-font-family: 'Poppins', 'Roboto', sans-serif;
```suggestion
  --rm-font-family: 'Noto Sans', 'Noto Serif', sans-serif;
```

2022-06-01 20:42 UTC, zoopmaster commented on src/components/custom-tom-select.scss
> +  z-index: var(--rms-z-index-dropdown);
```suggestion
  z-index: var(--rm-z-index-dropdown);
```

2022-06-01 21:10 UTC, zoopmaster commented on src/theme/base_theme.scss
> +  --rm-line-height-none:   0;
I'd like to make sure the whole scale is present.
```
--line-height-none:     0;
--line-height-densest:  1;
--line-height-denser:   1.15;
--line-height-dense:    1.3;
--line-height-base:     1.5;
--line-height-loose:    1.6;
--line-height-looser:   1.7;
--line-height-loosest:  1.8;
```

2022-06-07 13:19 UTC, scriswell commented on src/components/custom-tom-select.scss
>    margin-left: 6px;
@Jeremy-Walton Can we use our tokens here instead of the static styles for margin.

2022-06-07 13:19 UTC, scriswell commented on src/components/custom-tom-select.scss
>    border-left-color: #cacaca;
@Jeremy-Walton Can we use our tokens here instead of the static styles for color.

2022-06-07 13:20 UTC, scriswell commented on src/components/custom-tom-select.scss
>    padding: calc(8px - 2px) 8px calc(8px - 2px - 3px);
@Jeremy-Walton Can we use our tokens here instead of the static styles for padding. Some padding voodoo happening with this one.

2022-06-07 13:21 UTC, scriswell commented on src/components/custom-tom-select.scss
>    border: 1px solid #d0d0d0;
@Jeremy-Walton Can we use our tokens here instead of the static styles for border color.

2022-06-07 13:23 UTC, scriswell commented on src/components/flash.scss
>    border-left: solid 4px;
@Jeremy-Walton Can we use our tokens here instead of the static styles for border size.

2022-06-07 13:25 UTC, scriswell commented on src/components/form.scss
>    line-height: 1.5;
@Jeremy-Walton Can we use our tokens here instead of the static styles for line-height.

2022-06-07 13:30 UTC, scriswell commented on src/components/form.scss
>      border-radius: 50%;
@Jeremy-Walton We should use our tokens for radius here.

2022-06-07 13:35 UTC, scriswell commented on src/components/icon.scss
> +    font-size: 1.3em;
Can we use our font tokens here?

2022-06-07 13:36 UTC, scriswell commented on src/components/icon.scss
>      width: 3rem;
Magic numbers.

2022-06-07 13:40 UTC, scriswell commented on src/components/table.scss
> +    padding: 0.75rem var(--rm-space-medium);
Magic number in the padding value should be changed into a space token

2022-06-07 14:13 UTC, Jeremy-Walton commented on src/core/base.scss
>    font-weight: 400;
We have one, it just wasn't being used here.

```
@mixin font-weights {
  --rm-font-weight-light:     300;
  --rm-font-weight-normal:    400;
  --rm-font-weight-semi-bold: 600;
  --rm-font-weight-bold:      700;
}
```

2022-06-07 14:13 UTC, Jeremy-Walton commented on src/components/table.scss
>      font-weight: 400;
We have one, it just wasn't being used here.

```
@mixin font-weights {
  --rm-font-weight-light:     300;
  --rm-font-weight-normal:    400;
  --rm-font-weight-semi-bold: 600;
  --rm-font-weight-bold:      700;
}
```

2022-06-07 14:57 UTC, Jeremy-Walton commented on src/components/custom-tom-select.scss
>    background: #f2f2f2 !important;
Documented [here](https://github.com/RoleModel/rolemodel-design-system/issues/6), will address later.

2022-06-07 14:57 UTC, Jeremy-Walton commented on src/components/custom-tom-select.scss
>    background: rgba(0, 0, 0, 0.06) !important;
Documented [here](https://github.com/RoleModel/rolemodel-design-system/issues/6), will address later.

2022-06-07 14:57 UTC, Jeremy-Walton commented on src/components/form.scss
>    line-height: 1.5;
Documented [here](https://github.com/RoleModel/rolemodel-design-system/issues/7), will address later.

2022-06-07 14:58 UTC, Jeremy-Walton commented on src/components/form.scss
>    letter-spacing: 0.4px;
Documented [here](https://github.com/RoleModel/rolemodel-design-system/issues/7), will address later.

2022-06-07 18:25 UTC, scriswell requested changes
Just some small changes

2022-06-07 18:25 UTC, scriswell commented on src/components/icon.scss
> +  --mso-weight: var(--rms-font-weight-normal);
We should change the prefix from `--rms` to `--rm`.

2022-06-07 18:25 UTC, scriswell commented on src/components/icon.scss
> +  line-height: var(--rms-line-height-tight);
We should change the prefix from `--rms` to `--rm`.

2022-06-07 18:25 UTC, scriswell commented on src/components/icon.scss
> +  --mso-weight: var(--rms-font-weight-light);
We should change the prefix from `--rms` to `--rm`.

2022-06-07 18:25 UTC, scriswell commented on src/components/icon.scss
> +  --mso-weight: var(--rms-font-weight-normal);
We should change the prefix from `--rms` to `--rm`.

2022-06-07 18:25 UTC, scriswell commented on src/components/icon.scss
> +  --mso-weight: var(--rms-font-weight-semi-bold);
We should change the prefix from `--rms` to `--rm`.

2022-06-07 18:25 UTC, scriswell commented on src/components/icon.scss
> +  --mso-weight: var(--rms-font-weight-bold);
We should change the prefix from `--rms` to `--rm`.

2022-06-07 19:35 UTC, scriswell approved these changes

2022-06-07 19:52 UTC, merged